import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

const config = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    ignores: [
      'node_modules/**',
      '.next/**',
      'coverage/**',
      'data/**',
      'reports/**',
      'playwright-report/**',
      'test-results/**',
      // Generated by Next.js on every build.
      'next-env.d.ts',
      // Throwaway diagnostics, deliberately CommonJS so they can be run with a
      // bare `node scripts/ci/x.cjs` without a loader.
      'scripts/ci/*.cjs',
    ],
  },
  {
    rules: {
      // The correctness core and the parser are held to a stricter standard by
      // scripts/ci/check-invariants.mjs; these are project-wide baselines.
      '@typescript-eslint/no-explicit-any': 'error',
      'react/no-danger': 'error',
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          // `const { omitMe, ...rest } = obj` is the idiomatic way to drop a key;
          // the discarded binding is the point, not an oversight.
          ignoreRestSiblings: true,
        },
      ],
    },
  },
];

export default config;
